/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>

// Register Address
#define RCC_BASE   0x40021000
#define GPOIA_BASE 0x40010800

#define RCC_APB2ENR *(volatile long int *)(RCC_BASE + 0x18)
#define GPOIA_CRH   *(volatile long int *)(GPOIA_BASE + 0x04)
#define GPOIA_ODR   *(volatile long int *)(GPOIA_BASE + 0x0c)

int main(void)
{
	int delay = 100000;

	// Enable PORT.A
	RCC_APB2ENR |= (1<<2);

	// Bit Mode = 2
	GPOIA_CRH &= 0xff0fffff;
	GPOIA_CRH |= 0x00200000;

	/* Loop forever */
	while(1)
	{
		GPOIA_ODR |= (1<<13);	   // Set Pin.13
		for(int i=0; i<delay; i++); // Delay
		GPOIA_ODR &= ~(1<<13);	   // Clear Pin.13
		for(int i=0; i<delay; i++); // Delay
	}
}
